USE ReserveYourSport
GO

-- Table: Company
CREATE TABLE Company (
    CompanyId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL UNIQUE
);
GO

-- Table: Sport
CREATE TABLE Sport (
    SportId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(30) NOT NULL UNIQUE
);
GO

-- Table: Court
CREATE TABLE Court (
    CourtId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    CompanyId UNIQUEIDENTIFIER NOT NULL,
    SportId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (CompanyId) REFERENCES Company(CompanyId),
    FOREIGN KEY (SportId) REFERENCES Sport(SportId)
);
GO
